config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :grids, only: [:new, :create, :show] do
    resources :cases, only: [:edit, :update]
  end

  root to: 'pages#home'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/case.rb
class Case < ApplicationRecord
  belongs_to :grid

end

app/models/grid.rb
class Grid < ApplicationRecord
  belongs_to :user
  has_many :cases


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :grids
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  def edit
    @grid = Grid.find(params[:grid_id])
    @case = Case.find(params[:id])
  end

  def update
    @grid = Grid.find(params[:grid_id].to_i)
    @case = Case.find(params[:id].to_i)
    @case.update(value: params[:case] == "true", symbol: "X")
    redirect_to grid_path(@grid)
    @cases_left = @grid.cases.select { |cas| !cas.value }
    @machine_case = @cases_left.sample
    @machine_case.update(value: "true" == "true", symbol: "O")
  end


end

app/controllers/grids_controller.rb
class GridsController < ApplicationController
  def new
    @grid = Grid.new
    @grid.user = current_user
  end

  def create
    @grid = Grid.new(user: current_user)
    (1..9).to_a.each do |number|
      square = Case.new(position: number, grid: @grid)
      square.save
    end
    @grid.save
    redirect_to grid_path(@grid)
  end

  def show
    @grid = Grid.find(params[:id])
    @cases_left = @grid.cases.select { |cas| !cas.value }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :home ]
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cases/edit.html.erb
<h1>Case#edit</h1>
<p>Find me in app/views/case/edit.html.erb</p>

app/views/cases/update.html.erb
<h1>Case#update</h1>
<p>Find me in app/views/case/update.html.erb</p>

app/views/grids/new.html.erb
<h1>Un semblant de Tic Tac Toe</h1>
<p>Voulez-vous commencer une partie ?</p>
<div class="form-actions">
</div>

app/views/grids/show.html.erb
<div class="container">
  <h1>A vous de jouer !</h1>
  <div class="row row-cols-3">
    <% @grid.cases.order(:position).each do |cas| %>
      <div class="col border py-2" style="background-color: #bbad9f;">
        <%= form_tag grid_case_path(@grid, cas), method: :patch do %>
          <%= hidden_field_tag :case, !cas.value %>
          <%= submit_tag !cas.value ? " " : cas.symbol, class: 'h1 w-100', style: "height: 100px; background-color: #ede4da; border:none;" %>
        <% end %>
      </div>
    <% end %>
  </div>
  <% if @cases_left.length == 1 %>
      <%= link_to 'Allez viens, on rejoue ! ', grids_path, method: :post, class: 'btn btn-primary stretched-link my-3'  %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicTacToe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container w-50 text-center my-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Rules", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>